# CONNECT TO MONGO: sudo docker exec -it mongodb bash
# See all DBs: show dbs
# See all collections: show collections

# DOCKER COMPOSE ON AWS: https://gist.github.com/npearce/6f3c7826c7499587f00957fee62f8ee9
# Problem with docker-compose aws: https://forums.docker.com/t/couldnt-connect-to-docker-daemon-at-http-docker-localhost-is-it-running/87257/2
# ec2-54-166-93-83.compute-1.amazonaws.com

# DOCKER COMPOSE WITH SCALING
# sudo docker-compose up --scale web=3

# Run in AWS
# - Connect to the machine
# - Pull changes
# - sudo service docker start
# - sudo docker-compose up --scale web=3

version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
#    container_name: web
    ports:
      - "8087-8089:6000"
    links:
      - db

#  web2:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: web2
#    ports:
#      - "8088:6000"
#    links:
#      - db
#
#  web3:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: web3
#    ports:
#      - "8089:6000"
#    links:
#      - db

  html:
    build:
      context: ./Frontend/
      dockerfile: Dockerfile
    container_name: html
    ports:
      - "80:80"
    links:
      - web
#      - web2
#      - web3

  db:
    image: mongo:3.6.1
    container_name: db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    command: mongod

volumes:
  mongodb:
  mongodb_config: