# CONNECT TO MONGO: sudo docker exec -it mongodb bash
# See all DBs: show dbs
# See all collections: show collections

# DOCKER COMPOSE ON AWS: https://gist.github.com/npearce/6f3c7826c7499587f00957fee62f8ee9
# Problem with docker-compose aws: https://forums.docker.com/t/couldnt-connect-to-docker-daemon-at-http-docker-localhost-is-it-running/87257/2
# ec2-54-166-93-83.compute-1.amazonaws.com
version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "8087:6000"
    links:
      - db

  html:
    build:
      context: ./Frontend/
      dockerfile: Dockerfile
    container_name: html
    ports:
      - "80:80"
    links:
      - web
#    depends_on:
#      - db
#      - web

  db:
    image: mongo:3.6.1
    container_name: db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
#    ports:
#      - "27017:27017"
    command: mongod

#    expose:
#      - "1234"

#  nginx:
#    image: nginx:latest
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    depends_on:
#      - web
#    ports:
#      - "4000:4000"

volumes:
  mongodb:
  mongodb_config: